version: "3"

services:
  reelo-db:
    image: mysql:5.7
    container_name: reelo-db
    restart: always
    environment:
      MYSQL_DATABASE: reelo
      MYSQL_USER: reeloUser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  reelo-be:
    image: canobbioe/reelo-be
    ports:
      - 8080:8080
    depends_on:
      - reelo-db
    environment:
      - DB_DRIVER=mysql
      - DB_USER=reeloUser
      - DB_PASSWORD=password
      - DB_NAME=reelo
      - DB_HOST=reelo-db
    command: ./reelo

  reelo-fe:
    image: canobbioe/reelo-fe
    container_name: reelo-fe
    ports:
      - 80:80
    depends_on:
      - reelo-be
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro

